### ISSUE TITLE
Failed to create bn kernel on Resnet

### ISSUE THREAD

**Issue by WenyeLiu** [doonny/PipeCNN#113]
Hi, I have test pipecnn on the Terasic OpenVINO Starter Kit (OSK) which can run the Alexnet smoothly. While when I change the pipecnn for RESNET in hw_param.cl file, it will report the "failed to create bn kernel" message. I only change the network definition to RESNET in hw_param.cl and recompile the project. Any extra setting required for RESNET?

**Comment by doonny** [comment]
Please check the resource utilization in the report. There might not be enough hardware resource for the cyclone device

**Comment by WenyeLiu** [comment]
Thanks. I change the card to another PC and tune some hw params. Now it can run.

**Comment by mahinlma** [comment]
@WenyeLiu Facing same issue. Could you please share, what changes you made?

**Comment by WenyeLiu** [comment]
You can change the VEC_SIZE and LANE_NUM to a smaller value
