### ISSUE TITLE
Running on arria10sx dev kit

### ISSUE THREAD

**Issue by Nilsun9** [doonny/PipeCNN#116]
Hi @doonny thanks for a great work. I have a question, can I run this demo on Arria10sx development kit?  In case of DE5a-Net, it has a pcie but arria10sx doesn't have pcie interface. Do you think I can make it run on Arria10sx_devkit?

Thank you,
-Sunil

**Comment by doonny** [comment]
It works on a10-soc as long as you got the BSP for the board.
