### ISSUE TITLE
make: aocl :命令未找到

### ISSUE THREAD

**Issue by tmxklqy** [doonny/PipeCNN#12]
Dear Prof. Wang,
    I install Xilinx's SDAccel, but it display make: aocl: 命令未找到。Can ocal application on SDAccel?

**Comment by doonny** [comment]
you need to change VENDOR = altera to xilinx in the Makefile

**Comment by tmxklqy** [comment]
think you very much. Can you tell me  how to use SDAccel to run the project, I import the project but it shows "WARN	: Could not find any SDSoC projects."

**Comment by tmxklqy** [comment]
Dear Prof.Wang,
    I see in the last version, you said "Add support for Xilinx's SDAccel tool(2017.02)",  but I import you project it shows 
"make all 
make: *** 没有规则可以创建目标“all”。 停止。"
could you write a file which like a "READE.md" to introduce how to use SDAccel to run you project.

**Comment by doonny** [comment]
@tmxklqy Simply type make. there is no make all. The make follow is the same for altera and xilinx.

**Comment by tmxklqy** [comment]
thank you.
how to solve the problem: /usr/bin/ld: 找不到 -lxilinxopencl

**Comment by tmxklqy** [comment]
what is "Xilinx's OpenCL SDK toolset", it is SDAccel?

**Comment by doonny** [comment]
@tmxklqy Yes, it is SDAccel.
