### ISSUE TITLE
Xilinx KCU1500 Build failed,Unknown extension 'cl_intel_channels' - ignoring [-Wignored -pragmas];Unknown type name 'channel'

### ISSUE THREAD

**Issue by cococener** [doonny/PipeCNN#125]
So I want to know how did you use cl_intel_channels in the project?Or if you used it in the KCU1500 project.If you use it ,Can you tell me how to use it?And if you don't,can you tell me how to change the channel.

**Comment by doonny** [comment]
Please check the latest version for Xilinx
