### ISSUE TITLE
Main .io file not found

### ISSUE THREAD

**Issue by HemantaIngle** [doonny/PipeCNN#129]
hello, i  am trying to do this step- 
**_"Secondly, back to the main project folder, run the main makefile provided, and it will take around one hour to finish all the compilations. "_**
but i am getting the following error-
![Mainio error](https://user-images.githubusercontent.com/46565895/76710102-c8b13780-66c1-11ea-9d21-ecdfd62a8b86.JPG)

**Comment by doonny** [comment]
Please install gcc in the first place
