### ISSUE TITLE
DE10 hardware params

### ISSUE THREAD

**Issue by justinf2** [doonny/PipeCNN#130]
Hello, I'm trying to replicates the results found in demonstration section the PipeCNN paper for the DE-1 soc board and was wondering if it would be possible to get the hardware parameter settings used to create the bit-streams used to produce the results found in the paper.

**Comment by doonny** [comment]
Hi, the code has been modified for many times since the PipeCNN paper, so it is better to conduct another round of design space exploration to find out the best paras for the current version of code. We have not tested the latest code for DE-1 yet.

**Comment by justinf2** [comment]
Perfect. Thanks!
