### ISSUE TITLE
while making error- aoc command not found

### ISSUE THREAD

**Issue by HemantaIngle** [doonny/PipeCNN#134]
hello donny, 
it is great work by u which inspires novices like me, i get a error while doing make, it says "aoc command not found", can you please guide me through.Thanks.
![error](https://user-images.githubusercontent.com/46565895/79710285-65469680-8279-11ea-9626-fdda664daef3.JPG)

**Comment by doonny** [comment]
aoc is the key command of the OpenCL SDK.  Make sure you have correctly set the PATH. It is not an issue of this project

**Comment by mahinlma** [comment]
run this command to enable aoc
source <OpenCL_SDK_install_path>hld/init_opencl.sh
