### ISSUE TITLE
Cannot find board_env.xml in /intelFPGA_pro/19.1/hld/board/a10_ref，How can I fix it? Please

### ISSUE THREAD

**Issue by JDse7en** [doonny/PipeCNN#140]
when I "make"
error:Cannot find board_env.xml in /intelFPGA_pro/19.1/hld/board/a10_ref
How can I fix it? Please

**Comment by JDse7en** [comment]
the dir has a file name"board_env.xml",but it said connot find

**Comment by kutenai** [comment]
You must set the environment variable AOCL_BOARD_PACKAGE_ROOT to the directory that contains the board_env.xml. 

For example, if using a10_ref:
```
export AOCL_BOARD_PACKAGE_ROOT=$INTELFPGAOCLROOT/board/a10_ref
```

This assumes that the INTELFPGAOCLROOT is properly set to
```
export INTELFPGAOCLROOT=~/intelFPGA_pro/19.1/hld
```
