### ISSUE TITLE
"Error" aocl program

### ISSUE THREAD

**Issue by sergio14890** [doonny/PipeCNN#146]
Good morning people,
I come to try to clear a doubt with you, because you are the one who understands most of this matter.
I have 1 linux image on my fpga and I have the fpga connected to a screen via the vga output.
When I do:

aocl / dev / program conv.aocx

The screen is turned off and never turned on again.
Does anyone know why this happened, and what is the solution?
Thanks again to all.

**Comment by doonny** [comment]
it seems to be a BSP problem
