### ISSUE TITLE
How to get FPGA power consumption?

### ISSUE THREAD

**Issue by tommygyl** [doonny/PipeCNN#155]
I want to know how much power my FPGA is, and I haven't found a solution after referring to the manual. How is the power consumption measured in your paper?
And how to open aocl compiled project with quartus? I found that the software will report an error when directly opening the project containing all the kernels. The error is about cra_ring_node and so on.
Thank you very much! 十分感谢！

**Comment by doonny** [comment]
Here's the solution https://github.com/doonny/PipeCNN/issues/96
