### ISSUE TITLE
ModelZoo link is broken in User Instructions

### ISSUE THREAD

**Issue by Lissanro** [doonny/PipeCNN#157]
https://github.com/doonny/PipeCNN/tree/master/documents says "download the test vector and golden reference files from PipeCNN's own ModelZoo", but when I click "ModelZoo" link, I get 404 error.

**Comment by doonny** [comment]
It is pointing to the project/data folder

**Comment by Lissanro** [comment]
It is supposed to, but it is not, this is why I reported it. I checked again and the issue is still there. That link points to https://github.com/doonny/PipeCNN/tree/master/data which does not exist.

The right link is probably https://github.com/doonny/PipeCNN/tree/master/project/data (with "/project" before "/data").

**Comment by doonny** [comment]
removed the link.
