### ISSUE TITLE
How can i run this project in ZCU102 with SD card?

### ISSUE THREAD

**Issue by zhaobr340104** [doonny/PipeCNN#161]
I have been puzzled about some steps with ZCU102 implementation. Looking forward to reply for questions below. Thank you!
1.
![image](https://user-images.githubusercontent.com/30396886/114155427-11cecc00-9954-11eb-9a10-affdb891e904.png)
Which file should I attached to the "EDGE_COMMON_SW" parameter? I cannot find the 2020.1ZCU102 directory in your project. 

2.
I also attempted to create a Petalinux project after exporting the xsa file from Vivado2020.1. And I set the  "EDGE_COMMON_SW" parameter to my petalinux project. However, when I run "make image", the compile shows below ERROR.
![image](https://user-images.githubusercontent.com/30396886/114156758-7cccd280-9955-11eb-8688-fd7196334d0a.png)

SO, my question is about how to make a complete SD card image for ZCU102 board in this project.
Thank you very much for your answer! 
My Wechat account is zbr330232872. Welcome to contact with me for all of candidates in this project!

**Comment by doonny** [comment]
you need to download the common imagefiles(rootfs) from Xilinx's websit or generate it by using petalinux

**Comment by zhaobr340104** [comment]
Thank you very much for your help! Now I can 'make host' and 'make image' successfully!
I can see these files generated by 'make image'.
 
![image](https://user-images.githubusercontent.com/30396886/115948987-225e7500-a504-11eb-8b29-4d6b6a580df2.png)

![image](https://user-images.githubusercontent.com/30396886/115948982-1b376700-a504-11eb-95df-9f193354338c.png)
 
But when I put all these files in SD card,  the petalinux system cannot start.
When I checked the Xilinx official information, I found that there was a missing file called 'image.ub' for SD card.
 Do I have to generate image.ub or get this file in somewhere? 
Looking forward to your advice! Thank you!

**Comment by zhaobr340104** [comment]
I can run this project on ZCU102 with SD card now.
Step1: copy all of files in the "sd_card" directory into SD card fat32 partition.
Step2 : copy the Xilinx official rootfs system into SD card ext4 partition.
Thank you for your advice and your projcet!
