### ISSUE TITLE
Need information about your project !

### ISSUE THREAD

**Issue by TranQuocVietUIT** [doonny/PipeCNN#166]
Dear @doonny 
I want to ask you a few questions.
I noticed that you only have 1000 classes in your model (Example VGG16 model) defined in the file synset_words.txt . However, in the last full-connected layer your output node number is 1024 defined in the layer_config.h file. Why is there such a difference? How will the remaining 24 values be handled?
I hope to get an early response from you. 
Thank you.

**Comment by doonny** [comment]
The 1000 classes are padding with 24 NULL to form a 1024 vector for easy of coding
