### ISSUE TITLE
Make host error, no opencl header files, ZCU102/Vitis/Xilinx

### ISSUE THREAD

**Issue by qiuzeyu** [doonny/PipeCNN#176]
Hello, I am trying to compile this project for the Xilinx ZCU102 board on Ubuntu18.04.2 64-bit. According to the **_README.md_**  under **_documents_** folder, the **_make fpga_** command is successfully executed, and the **_conv.xclbin_** file is generated. But when I execute the **_make host_** command, the following error occured:
![image](https://user-images.githubusercontent.com/44024485/222677610-fdcc4ff9-5650-45c2-bcc4-402729a0efcd.png)

 I have installed Vitis 2020.1 and Xilinx Runtime(XRT)2020.1 on Ubuntu, but there is no **_opencl.h_** file in the XRT installation path：
![image](https://user-images.githubusercontent.com/44024485/222678307-9ab1bfdd-372a-4792-b990-361a5def3f75.png)

I also installed the opecnCL library for Ubuntu and found **_opencl.h_** in the `/usr/include/CL` path:
![image](https://user-images.githubusercontent.com/44024485/222680792-534f0cd9-46a7-45e7-b8be-1457dfbd7735.png)

Then I executed the following command and compile again:
**`export CPLUS_INCLUDE_PATH=/opt/xilinx/xrt/include/:/usr/include`**
new errors appeared:
![image](https://user-images.githubusercontent.com/44024485/222681607-106d025b-1267-4f8e-aa0d-9edee5f441c5.png)

I don't understand what's wrong. How can I get the right **_opencl.h_** file please？ And is there a more specific tutorial on compiling this project for Xilinx ZCU102 board? 

This is my **Makefile**, please help me.
[Makefile.txt](https://github.com/doonny/PipeCNN/files/10880514/Makefile.txt)

Thank you.

**Comment by zyt1024** [comment]
hello,你的解决问题了嘛?

**Comment by zyt1024** [comment]
我的也报错..

**Comment by zyt1024** [comment]
你的解决了嘛，我的也报错，不知道为什么
![image](https://user-images.githubusercontent.com/42999008/226583189-5e820dd5-a405-4317-b291-839249d32489.png)

**Comment by qiuzeyu** [comment]
> 你的解决了嘛，我的也报错，不知道为什么 ![image](https://user-images.githubusercontent.com/42999008/226583189-5e820dd5-a405-4317-b291-839249d32489.png)

这个是因为common文件夹下的ocl_util.cpp没有编译，把Makefile中编译host的命令改成Intel的再make host：
![image](https://user-images.githubusercontent.com/44024485/226793017-7b3a5836-16cf-497d-9e42-e58732af5864.png)

**Comment by qiuzeyu** [comment]
此错误已解决，问题是缺少petalinux SDK造成的。部署PipeCNN到ZCU102上，除了安装Vitis和Petalinux工具之外，还需要从Xilinx官网下载安装ZynqMP通用镜像，镜像压缩包内包含了制作SD卡系统的Linux内核及根文件系统。解压后按照压缩包内的readme说明在指定路径下（需修改Makefile中EDGE_COMMON_SW的路径与此相同）执行sdk.sh安装SDK，SDK中提供了编译host程序所需的OpenCL头文件：
![image](https://user-images.githubusercontent.com/44024485/226803731-703d3cd2-f4c7-44dd-9700-c8a7a32f1efe.png)
