### ISSUE TITLE
Best Parameter Setting on KCU1500 Board?

### ISSUE THREAD

**Issue by hanwgyu** [doonny/PipeCNN#19]
Hello, Prof. Wang.

I'm trying to run on KCU1500 board.
What is a best parameter setting of VEC_SIZE, LANE_NUM, CONV_GP_SIZE_X?

When I tried VEC_SIZE=8, LANE_NUM=16, then an error occurred like as below.

<img width="1263" alt="2017-11-06 8 40 50" src="https://user-images.githubusercontent.com/22293149/32439651-fb9c001a-c332-11e7-9df7-81710a324ad8.png">

Thank you.

**Comment by xuke225** [comment]
Hello, hanwgyu.
after you setting VEC_SIZE  and  LANE_NUM you should  cd  in device file and generate pipe.cl
use like this:
`python pipe_gen.py [lane_num] [vec_size]`

**Comment by wjqwsp** [comment]
@hanwgyu Hello,have you tried running vgg16 on kcu1500?
