### ISSUE TITLE
Cannot find CONV_GP_SIZE_X

### ISSUE THREAD

**Issue by davidsai** [doonny/PipeCNN#2]
Hi,

I am trying to get this project running on Cyclone-V SEA5. The configuration you've used is V=8,L=8,GP_X=7, where GP_X is CONV_GP_SIZE_X. But I cannot find CONV_GP_SIZE_X anywhere in the code. Could you tell where can I set this variable?

Thank you in advance!

**Comment by doonny** [comment]
Hi, please check out the latest updates.

**Comment by doonny** [comment]
@davidsai Hi, please close this issue if there are no further questions.
