### ISSUE TITLE
AWS F1 Build failing 

### ISSUE THREAD

**Issue by shrivinayak** [doonny/PipeCNN#20]
Linking failed in Emulation-HW for AWS F1. 
Hardware Platform: xilinx_aws-vu9p-f1_4ddr-xpr-2pr_4_0

![screenshot from 2017-11-20 10-09-04](https://user-images.githubusercontent.com/12874569/33028375-cfb805d2-cde3-11e7-9188-ab129ac4a5aa.png)

**Comment by doonny** [comment]
There is some issues with HW-EMU with SDx, please do not use it. Xilinx will fix this in the later vision.
Please use SW-EMU and HW mode only.

**Comment by shrivinayak** [comment]
Thank you!
