### ISSUE TITLE
DTYPE and MACTYPE

### ISSUE THREAD

**Issue by AndrewSivrit** [doonny/PipeCNN#22]
Hi, thank you for your project.
What kind difference should be  between DTYPE and MACTYPE. In your example char (8 bit) and int (32 bit).
If I want to use DTYPE short (16 bit), what MACTYPE I should choose ?
Long int (64 bit) ? Or need to rounding and truncate immedietly after every multiplication ?

**Comment by doonny** [comment]
DTYPE is the data type you truncated for weight and activation.
MACTYPE refers to the precision of the accumulator. You need to make sure that the precision of the accumulator are high (long) enough to avoid possible overflow
