### ISSUE TITLE
a problem about running the project in sdaccel gui

### ISSUE THREAD

**Issue by wjqwsp** [doonny/PipeCNN#25]
I put the image.dat,weights.dat and fc8.dat in the data folder, build and run the project in cpu emulation mode.The build process finishes successfully.However, when I attempt to run the exe file,it finishes so quick and no errors occur.The console output is very short:

``` shell
***************************************************
PipeCNN: An OpenCL-Based FPGA Accelerator for CNNs 
***************************************************

61063552 total weights read 
154587 bytes image read 
```

I'm using SDaccel 2017.2 gui mode.Why is the output log so short?I don't see any output files created after I run the project.

**Comment by wjqwsp** [comment]
I try the make compiling flow, and the output is similar.But this time I know it fails:
``` shell
[root@gitlabci src]# ./run.exe conv.xclbin 
***************************************************
PipeCNN: An OpenCL-Based FPGA Accelerator for CNNs 
***************************************************

61063552 total weights read 
154587 bytes image read 
Segmentation fault (core dumped)
```

How can I solve this?

**Comment by wjqwsp** [comment]
I have fixed it.The issue will be closed.

**Comment by sinatv52** [comment]
@wjqwsp  may you pls say what was the problem? thanks
