### ISSUE TITLE
BSP for DE1-soc

### ISSUE THREAD

**Issue by SmartRoof** [doonny/PipeCNN#29]
Hi sir,
According to the description, the version of  Intel's OpenCL SDK v16.1 is used in this project. 
We would like to test run the program on the Terasic De1-SoC board. 
But we found only the BSP for Altera SDK OpenCL 16.0 is provided in the official webpage.
Is it the one you used in this project?
And is it work fine in Intel's OpenCL SDK v16.1?

![capture](https://user-images.githubusercontent.com/19350260/33745847-40d1abd8-dbf4-11e7-8d96-177ebd2a8f2d.PNG)

Thank you

**Comment by thinkoco** [comment]
Yes,it's OK. It contains the same version of the driver in 16.0 and 16.1.Hardware template can be compiled  in  16.1 and runtime is ok

**Comment by doonny** [comment]
v17.0 is also OK.
