### ISSUE TITLE
error: Channel support is not enabled

### ISSUE THREAD

**Issue by LCF2016** [doonny/PipeCNN#34]
Hi,I compiled project with Intel OpenCL SDK for FPGA 17.1 and get the following error
In file included from /home/wangjf/PipeCNN/project/__all_sources.cl:2:
PipeCNN/project/device/conv_pipe.cl:75:24: error: Channel support is not enabled
channel channel_vec    data_ch    __attribute__((depth(0)));

Anyone got an idea? Thanks in advance!!

**Comment by LCF2016** [comment]
I changed OPENCL_EXTENSION to OPEN EXTENSION  which can solve the above problem.
thanks!

**Comment by bagumondigi** [comment]
I have solved the problem by following this thread in Altera forum: https://www.alteraforum.com/forum/showthread.php?t=57424
in conv_pipe.cl change to: #pragma OPENCL EXTENSION cl_intel_channels : enable

**Comment by lihao2333** [comment]
for `aoc` with version 17.1, you should do two thing in `conv_pipe.cl`  
1. change OPENCL_EXTENSION to OPENCL EXTENSION
2. replace all `altera` into `intel` in this file
