### ISSUE TITLE
make: *** [conv.aocx] Error 1

### ISSUE THREAD

**Issue by LCF2016** [doonny/PipeCNN#35]
Hi,I compiled the project based on de10-standard,but it implied that LABs isn't enough.What's the solution?
aoc: First stage compilation completed successfully.
Compiling for FPGA. This process may take a long time, please be patient.
Error (170012): Fitter requires 4243 LABs to implement the design, but the device contains only 4191 LABs
Error: Cannot fit kernel(s) on device
Makefile:135: recipe for target 'conv.aocx' failed
make: *** [conv.aocx] Error 1

Thanks

**Comment by doonny** [comment]
Please refer to the user instructions, section Configuration.
Use a smaller value of VEC_SIZE and LANE_SIZE
