### ISSUE TITLE
-bash: ./run.exe: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by LCF2016** [doonny/PipeCNN#36]
Hi,I complied with FLOW=sw_emu and it can be complied successfully.But when I executed command like this:
#./run.exe conv.aocx
-bash: ./run.exe: cannot execute binary file: Exec format error

Anyone got a idea?
Thanks very much.

**Comment by Alhad1994** [comment]
Hi, I am getting the same error while running conv.aocx. How did you fix it?Moreover I already have executed sw_steup_emu.sh provided.
![sw_emu_error](https://user-images.githubusercontent.com/26221839/81269646-78d65900-8ffe-11ea-9e1c-addd56c702e4.png)
 Also if i run the command like below it gives error.

**Comment by kingkoobe** [comment]
Did you figure it out?

**Comment by doonny** [comment]
you should first set emulation env
