### ISSUE TITLE
Floating point and fixed point

### ISSUE THREAD

**Issue by johnnydept** [doonny/PipeCNN#38]
hi Prof @doonny  , I noticed the current version is in fixed point mac. And how was the resource utilization compared to Floating point mac?
 What is the Pipe depth ?
`` #define PIPE_DEPTH          6 ``

**Comment by doonny** [comment]
There is no floating point version.

PIPE_DEPTH refers to the depth of the accumulate buffers.

**Comment by johnnydept** [comment]
[`History:`]
`-v1.0 Initial release`
https://github.com/doonny/PipeCNN/blob/01799e66f69f4ce7dc123795717b1f3e0ab8aeb0/project/device/conv_pipe.cl
Here you uses float for both data and weight. 
`float mac(lane_data input, lane_data weights)`
I read your paper, you got 33.9GOPS when running on Stratix-V (floating point)

**Comment by doonny** [comment]
Floating-point format is no longer supported.
