### ISSUE TITLE
ERROR: CL_INVALID_BINARY 

### ISSUE THREAD

**Issue by ArjunaDeSoysa** [doonny/PipeCNN#57]
Dear Prof. @doonny ,
I use De1-SoC and Angstrom v2014.12 - Kernel , I changed,
`const char *vendor_name = "altera";` in derictory ../project/host/main.cpp
because of when *vendor_name = "Intel" there was Error "Unable to find the desired OpenCL platform." 

now there is new error;

```
./run.exe conv.aocx
***************************************************
PipeCNN: An OpenCL-Based FPGA Accelerator for CNNs
***************************************************
Platform: Altera SDK for OpenCL                                                           
Using 1 device(s)                                                                         
  Device 0: de1soc_sharedonlyCyclone V SoC Development Kit                                
Device OpenCL Version: OpenCL 1.0 Altera SDK for OpenCL, Version 16.0                     
Device Max Compute Units: 1                                                               
Device Max WorkGroup Size: 2147483647                                                     
Device Max WorkItem Size: 2147483647                                                      
Device Global Memory Size: 512 MBytes                                                     
Device Local Memory Size: 16 KBytes                                                       
Device Max Clock Freq: 1000 Mhz 


Loading kernel/binary from file conv.aocx 
ERROR: CL_INVALID_BINARY
Location: ../common/ocl_util.cpp:415
Failed to create program with binary
```

So i want to know, There are another things do i want to change ? (because of changing `const char *vendor_name = "altera";`)?

Thank You

**Comment by ArjunaDeSoysa** [comment]
Dear @thinkoco do you know how to slove this problem?

**Comment by thinkoco** [comment]
@ArjunaDeSoysa  So, you have use the opencl sdk 16.0 runtime file and rebuild driver?
It's recommend to use sdk 16.1 runtime file.

**Comment by ArjunaDeSoysa** [comment]
@thinkoco yes i use opencl sdk 16.1 runtime file in host computer. But in terasic site there's only have BSP(Board Support Package) for Altera SDK OpenCL 16.0. i saw that someone say that it is okay for this pipeCNN.

**Comment by thinkoco** [comment]
@ArjunaDeSoysa   Also, you can use my SD card image [c5soc_opencl_lxde_all_in_one_180317.img](https://drive.google.com/open?id=1mAYHFvOw2xtgf-e8pntFCxCGOdaYNsgG).
Just need to replace the dtb with no vga one  [here](https://github.com/doonny/PipeCNN/files/1821204/socfpga_cyclone5_de1soc_novga.dtb.zip)
and delete the CL_CONTEXT_COMPILER_MODE_ALTERA=3  flag in the init_opencl16.1.sh file.

**Comment by ArjunaDeSoysa** [comment]
Okay I'll try that. Thank you very much @thinkoco.

**Comment by ArjunaDeSoysa** [comment]
@thinkoco , 1) Do i want to replace the socfpga_cyclone5_de1soc_novga.dtb with socfpga.dtb **or** de1soc_socfpga.dtb(inside the de1soc folder )?

2) I use UART to USB cable so , username : knat and password : knat right?

i am really sorry for the bothering again and again.

**Comment by thinkoco** [comment]
@ArjunaDeSoysa  cover the socfpga.dtb with socfpga_cyclone5_de1soc_novga.dtb , and keep  the socfpga.dtb name. x2go user is knat,  root for uart.

**Comment by ArjunaDeSoysa** [comment]
@thinkoco , Still i got same error,

```
root@C5SoC:~# source init_opencl_16.1.sh                                        
root@C5SoC:~# cd cnn                                                            
root@C5SoC:~/cnn# ./run.exe conv.aocx                                           
******************************************                                      
An OpenCL-Based FPGA Accelerator for CNNs                                       
******************************************                                      
                                                                                
Platform: Intel(R) FPGA SDK for OpenCL(TM)                                      
Using 1 device(s)                                                               
  Device 0: de1soc_sharedonly_vga : Cyclone V SoC Development Kit               
Device OpenCL Version: OpenCL 1.0 Intel(R) FPGA SDK for OpenCL(TM), Version 16.1
Device Max Compute Units: 1                                                     
Device Max WorkGroup Size: 2147483647                                           
Device Max WorkItem Size: 2147483647                                            
Device Global Memory Size: 512 MBytes                                           
Device Local Memory Size: 16 KBytes                                             
Device Max Clock Freq: 1000 Mhz                                                 
                                                                                
Loading kernel/binary from file conv.aocx                                       
ERROR: CL_INVALID_BINARY                                                        
Location: ../common/ocl_util.cpp:415                                            
Failed to create program with binary  
```
at the beginning(not only this time) there's not appear in this part below ;

```
61063552 total weights read 
154587 bytes image read 
1024 total output reference read 
```
i tried various thing. can you please help me to solve this?

**Comment by ArjunaDeSoysa** [comment]
@thinkoco , you are right. i check `aocl board-xml-test` in the host computer, the result is in given below;
```
arjuna@arjuna-Inspiron-3542:~$ source /etc/profile
arjuna@arjuna-Inspiron-3542:~$  aocl board-xml-test 
 board-path       = /home/arjuna/intelFPGA/16.1/hld/board/terasic/de1soc

 board-version    = 13.0

 board-name       = de1soc

 board-default    = de1soc

 board-hw-path    = /home/arjuna/intelFPGA/16.1/hld/board/terasic/de1soc/./de1soc

 board-link-flags = -L/home/arjuna/intelFPGA/16.1/hld/board/terasic/de1soc/arm32/lib -L/home/arjuna/intelFPGA/16.1/hld/host/arm32/lib

 board-libs       = -lalterammdpcie -lstdc++

 board-util-bin   = /home/arjuna/intelFPGA/16.1/hld/board/terasic/de1soc/arm32/bin

```
The **bord-version is 13.0**. i think that is the problem. i download BSP(Board Support Package) in terrasic site. I serched BSP 16.1 to download and i coulden't find it.

Can you please send me the link , where can i download  BSP(Board Support Package) for Altera SDK OpenCL 16.1 .?

**Comment by thinkoco** [comment]
@ArjunaDeSoysa  it seems to be  the board xml or hardware template version. It's not the SDK version. Before you building and running the host, check not setting the CL_CONTEXT_EMULATOR_DEVICE_ALTERA flag.Also ,some other flags.I have test the PipeCNN on my baord with my sd card image , It's OK. if  I set CL_CONTEXT_EMULATOR_DEVICE_ALTERA = 1 and run, get you same error. Maybe, not your same issue, but you can check it.

**Comment by doonny** [comment]
you need firstly to reprogram the fpga manually on the DE1 platform

**Comment by ArjunaDeSoysa** [comment]
Prof. @doonny did you mean,
run aocl program `aocl program /dev/acl0 conv.aocx` before `./run.exe conv.aocx` ?

**Comment by doonny** [comment]
yes

**Comment by doonny** [comment]
you could also use aocl diagnose to verify that you have the right driver installed.

**Comment by ArjunaDeSoysa** [comment]
yes it worked. Thank you very much thinkoco and Prof. doonny

**Comment by Fnajjar** [comment]
Hi @doonny ,  @thinkoco , 
I am using the OpenCL SDK v17.1, and having the same error. 
What shall I do??

**Comment by thinkoco** [comment]
@Fnajjar PCIE based board ?  you can try to test the runtime with the "aocl diagnose" or "aocl program" command first.

**Comment by DasunBhanuka** [comment]
@thinkoco  @doonny  If I rename the folder 'de1soc_sharedonly' to 'de1soc', will the following get resolved?

```
Loading kernel/binary from file conv.aocx
ERROR: CL_INVALID_BINARY
Location: ../common/ocl_util.cpp:415
Failed to create program with binary
```

**Comment by thinkoco** [comment]
@DasunBhanuka  No.
1. check the conv.aocx for which device by "aocl binedit conv.aocx get .acl.board board.txt && cat board.txt"
2. check the opencl.rbf for which device by "aocl diagnose"
they must be same device name.

**Comment by Fnajjar** [comment]
Hey @thinkoco, @DasunBhanuka  
I tried the instruction but still have the same error
What do you think?

![beniedit](https://user-images.githubusercontent.com/38285230/39173237-6f68a23c-47a4-11e8-83ba-5a98f690c070.png)

**Comment by DasunBhanuka** [comment]
@thinkoco  @Fnajjar  @aazz44ss @doonny 

I am getting the exact same error just like this.. even though I am running **OpenCl 16.1**  Can you give us another idea?

**Comment by thinkoco** [comment]
@Fnajjar  There may be some difference in 
1. aocl binedit conv.aocx list
2. "aocl binedit conv.aocx get .acl.board_spec.xml board.xml && cat board.xml"  or other file

**Comment by Fnajjar** [comment]
@thinkoco , actually i did the commandes and it seems that there 's no ".acl.board_spec.xml " 

![acl_board](https://user-images.githubusercontent.com/38285230/39176134-52c52508-47ac-11e8-98f6-f70857b53b13.png)

**Comment by thinkoco** [comment]
@Fnajjar nothing in the .acl.board ?

**Comment by Fnajjar** [comment]
@thinkoco, How shall I know? 
I tried "aocl binedit conv.aocx get .acl.board board.xml && cat board.xml" and I've got nothing :(

**Comment by thinkoco** [comment]
@Fnajjar It seem to be an emulater .aocx file, there is no .acl.fpga.bin in the conv.aocx.
if emulater, try  "export CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1" before running host

**Comment by Fnajjar** [comment]
thank you @thinkoco , I did it and this time I have different error,
please find the image below! 
![emula](https://user-images.githubusercontent.com/38285230/39179106-bc4bad24-47b3-11e8-85de-b2e8b89bf488.png)

**Comment by thinkoco** [comment]
@Fnajjar It's Ok,you need downlaod the  PipeCNN weight files [here](https://github.com/doonny/PipeCNN/tree/master/data).

**Comment by Fnajjar** [comment]
@thinkoco, actually I have already uploaded them "/home/najjar/Documents/PipeCNN-master/data", *the problem is that it's not beeing detected or can't been found 
![data](https://user-images.githubusercontent.com/38285230/39185133-69d87cee-47c6-11e8-8b33-a65551e9a177.png)

**Comment by thinkoco** [comment]
@Fnajjar Also, data_alex is needed.see the host code and the path
```
const char *weight_file_path = "./data/data_alex/weights.dat";
const char *input_file_path = "./data/data_alex/image.dat";
const char *ref_file_path = "./data/data_alex/fc8.dat";
const char *dump_file_path = "./result_dump.txt";
```

**Comment by DasunBhanuka** [comment]
Dear @thinkoco 

How to check this in fpga,

aocl binedit conv.aocx list
"aocl binedit conv.aocx get .acl.board_spec.xml board.xml && cat board.xml

as you said..

**Comment by Fnajjar** [comment]
@thinkoco thank you very much for your help acctually it works! I already uploded the data_alex. 
I moved the files "conv.aocx" and the "run.exe" in the folloing path "/home/najjar/Documents/PipeCNN-master" and it worked! 
![1](https://user-images.githubusercontent.com/38285230/39189974-e2e923ec-47d3-11e8-8477-2324580af67b.png)
![2](https://user-images.githubusercontent.com/38285230/39189975-e3008802-47d3-11e8-8c9b-3215823f5536.png)

**Comment by ArjunaDeSoysa** [comment]
@Fnajjar if you able to complete the HW emulation also you can help to @DasunBhanuka to get it work. cause you both have same problem right. Thank You.

**Comment by DasunBhanuka** [comment]
@Fnajjar   Can you please explain  how you made it work, after that error..

**Comment by Fnajjar** [comment]
@DasunBhanuka, well when I had the "ERROR: CL_INVALID_BINARY" I juste tiped the commande line "export CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA" and the he still couldn't find the weights eventhough, I had the data in the wright directories.
So, I just moved the two files "conv.aocx" and the "run.exe" in the folloing path "/home/user/Documents/PipeCNN-master" and it worked!

![final](https://user-images.githubusercontent.com/38285230/39191193-b417d402-47d6-11e8-9add-24faa3c00502.png)

**Comment by DasunBhanuka** [comment]
@Fnajjar  Will you also try this using a FPGA hardware?

**Comment by Fnajjar** [comment]
well now since it's working on emulator, I am going to implement it on a Attila Arria 10 Gx
but, I am trying to know how to do that?
Do you have an idea??

**Comment by DasunBhanuka** [comment]
@Fnajjar  I am currently trying to implement it on Altera DE1SoC. If it works, I'll tell you..

**Comment by thinkoco** [comment]
@DasunBhanuka Sorry for notice that  aocl diagnose on de1soc and aocl binedit  on PC

**Comment by thinkoco** [comment]
@DasunBhanuka 
1.you can use "aocl diagnose" command after sourcing the opencl initial shell file on de1soc. 
2. then "aocl binedit conv.aocx list" and  "aocl binedit conv.aocx get .acl.board board.txt && cat board.txt" on PC
3. both the device names in step 1 and step 2 should be the same one.

**Comment by DasunBhanuka** [comment]
@thinkoco  I did as you said,
![screenshot from 2018-04-24 22-09-55](https://user-images.githubusercontent.com/38661801/39196607-b9042304-480c-11e8-9226-0deb54ab2ee1.png)
It is not same..

**Comment by DasunBhanuka** [comment]
Dear @thinkoco 
I did as you said..
![screenshot from 2018-04-24 22-17-10](https://user-images.githubusercontent.com/38661801/39196830-46f348de-480d-11e8-9961-c6761a3e100e.png)
Here's the result

**Comment by DasunBhanuka** [comment]
Dear @thinkoco why do you think I get the error `No such file or directory` Or Am I missing something here?

**Comment by thinkoco** [comment]
@DasunBhanuka Hi,  you can cd to the folder which contians conv.aocx first .Also,read permissions of this file

**Comment by DasunBhanuka** [comment]
@thinkoco Can you send me the files you created for DE1SoC? conv.aocx & run.exe
Will they be compatible with my board?

**Comment by Frankzd** [comment]
Hi@Fnajjar，I am using Arria 10 Gx, and 17.1 SDK just like you. And I am facing the problem you might met before 

![微信截图_20190319193547](https://user-images.githubusercontent.com/13731304/54603018-3f4f3100-4a7e-11e9-9983-ba4fefc8f071.png)

Do you have any idea how to solve this problem?

**Comment by Frankzd** [comment]
Hi @Fnajjar，I am using Arria 10 Gx, and 17.1 SDK just like you. And I am facing the problem you might met before. Do you have any idea how to solve this problem?
