### ISSUE TITLE
Using different frac_w for weights and bias

### ISSUE THREAD

**Issue by hammadj** [doonny/PipeCNN#65]
Is it possible to use a different frac_w for the bias and for the weights? My biases values are much larger than my weight values so finding an appropriate frac_w for both of them is difficult. If I regenerate my weights using different frac_w for the biases, and then update main.cpp and conv_pipe.cl to take this new parameter into account, would that work?

**Comment by doonny** [comment]
Yes, you can set different values for frac_w, but you need to change the code at where the bias is added to the final results.
