### ISSUE TITLE
The configuration of DE5a in the paper and RAM needed for syntheses

### ISSUE THREAD

**Issue by myih** [doonny/PipeCNN#66]
Hi professor @doonny 

I'm curious about the configuration (vector, lane) you used for DE5a to achieve 5ms for Alexnet in the paper. 
I tried to test it myself with my Arria10GX board, but with  (vector=16, lane=64 or 48) the syntheses failed because my 32Gb RAM was not enough. 
Also, why didn't you use more resources with the DE5a when there's still resources left?

Thank you!

**Comment by doonny** [comment]
For arria10 device, you need at least 64GB RAM for your PC.
And try to compile the design in flat mode. It is recommended by Intel.

**Comment by myih** [comment]
Thanks @doonny 
I compiled the aocx on another machine with more RAM, with (vector=16, lane=64) the runtime for Alexnet is 11.1ms on my Arria10GX.  I use flat mode and no profile. Could you tell me what configuration can achieve 5ms for Alexnet? 
Thank you!

**Comment by laski007** [comment]
Dear @myih Do you mind to tell me what command should I use to specify "flat mode" when I compile? Thank you so much!

**Comment by myih** [comment]
@laski007 Use flag -bsp-flow=flat

**Comment by laski007** [comment]
Dear @myih Thank you so much!! BTW, do you mind to tell me or give me some links to introduce what is "flat mode" and its benefit?

**Comment by laski007** [comment]
Dear Prof. Wang @doonny , do you mind to tell me what is flat mode and its benefit? Many thanks.

**Comment by laski007** [comment]
@CrazyBingo 找不到庫是環境變量的設置問題，我感覺你大概需要把該路徑添加到系統的環境變量中。
