### ISSUE TITLE
如何测量FPGA的工作频率和功率？

### ISSUE THREAD

**Issue by HulkSun** [doonny/PipeCNN#68]
你好， @doonny 
我在论文实验结果对比中看到有FPGA的Frequency和Board Power这两项指标，请问您是如何测量FPGA工作时的工作频率和功率的？
谢谢！

**Comment by aazz44ss** [comment]
功率可以外接功率計，有些廠牌FPGA有內建的量測method，您可能要和vendor詢問
工作頻率是在compile後會有硬體報告，在Arria10為top_report.txt或是aocl_report.txt

**Comment by HulkSun** [comment]
好的，谢谢 @aazz44ss
