### ISSUE TITLE
Some problems encounted when compiling using De0-Nano-SoC board

### ISSUE THREAD

**Issue by roddregs** [doonny/PipeCNN#69]
@doonny 
Hi Sir, good day!
Tried to compile PipeCNN in Deo-Nano-SoC board.
However, I encountered the following problem when running the main makefile:
g++   ./host/main.o ../common/ocl_util.o ../common/timer.o -o run.exe -L/thesis/intelFPGA/16.1/hld/board/de1soc/arm32/lib -L/thesis/intelFPGA/16.1/hld/host/arm32/lib -L/thesis/intelFPGA/16.1/hld/host/linux64/lib -Wl,--no-as-needed -lalteracl -lalterahalmmd -lalterammdpcie -lelf 
/usr/bin/ld: cannot find -lalterammdpcie
collect2: error: ld returned 1 exit status
Makefile:118: recipe for target 'run.exe' failed
make: *** [run.exe] Error 1
Is Deo-Nano-SoC board compatible with the configurations of PipeCNN?
Thank you very much for your reply in advance, Sir doonny...

**Comment by doonny** [comment]
Do you mean DE10-nano ?

**Comment by roddregs** [comment]
Sir @doonny, it's De0-nano board, cyclone 5 from terasic.

**Comment by doonny** [comment]
I don't think there is a OpenCL BSP for DE0-nano board.

**Comment by zhenyu707** [comment]
Hello @doonny  @roddregs ,

I am trying to run this in De10-nano but there is some error. May I know how to solve this? 
![capture](https://user-images.githubusercontent.com/13069077/39052932-26be101a-44e0-11e8-87d9-cfc7af331542.PNG)

For your information, threre is a OpenCL BSP for De10-nano and this is the link : 
[http://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&No=1046&PartNo=4](url)

**Comment by doonny** [comment]
The cyclone device does not support emulator model.

**Comment by zhenyu707** [comment]
Hello @doonny ,

Would this error be solved if I run on De10-Standard?

Thank you.

**Comment by doonny** [comment]
All SoC-FPGA does not support emualtor model. You need to use PCIE-based bsp.

**Comment by CrazyBingo** [comment]
# @
![image](https://user-images.githubusercontent.com/20455690/39901425-f80956be-54fa-11e8-892a-5a6b949f9b40.png)
the same as you,  @zhenyu707 , have you ever resolve it?(my board is de10 .too)

**Comment by zhenyu707** [comment]
@CrazyBingo  Hello, the problem still can not be solved.
