### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by HulkSun** [doonny/PipeCNN#71]
https://github.com/doonny/PipeCNN/blob/3bf485ad2cac3957af6ca17e2b6c6a1477962894/project/host/main.cpp#L1616 这个地方的mean_data使用完后没有释放空间，长时间运行会导致内存泄漏问题。

**Comment by DasunBhanuka** [comment]
Dear @HulkSun,
When i compile the ./run.exe conv.aocx (two generate file from the host computer) in my arm based DE1-SOC FPGA, the error occurs,

```
Loading kernel/binary from file conv.aocx
ERROR: CL_INVALID_BINARY
Location: ../common/ocl_util.cpp:415
Failed to create program with binary
```
and
in location : ../common/ocl_util.cpp:415 there is;

```
#ifdef FPGA_DEVICE
  cl_program program = clCreateProgramWithBinary(context, num_devices,devices,         binary_lengths,
    (const unsigned char **) binaries.get(), binary_status, &status);
  checkError(status, "Failed to create program with binary");
```
What do you think the problem is ?
