### ISSUE TITLE
weights

### ISSUE THREAD

**Issue by songxujiangyang** [doonny/PipeCNN#72]
你好，可以向您请求一下const char *weight_file_path = "./data/data_alex/weights.dat";
const char *input_file_path = "./data/data_alex/image.dat";
const char *ref_file_path = "./data/data_alex/fc8.dat"
这些权值文件吗，我想先在电脑上跑通您的程序在一点点修改。。

**Comment by HulkSun** [comment]
[https://github.com/doonny/PipeCNN/tree/master/data](url) 
先看项目结构和readme
