### ISSUE TITLE
Implement 3-dimensional (3-D) multiply-accumulate (MAC) by using a HLS-friendly 1-D convolution structure which flattened the 3-D convolution

### ISSUE THREAD

**Issue by ArjunaDeSoysa** [doonny/PipeCNN#73]
Dear @aazz44ss, @doonny  I have a problem in the topic as i said, how can convert in 3-D  MAC using 1D and the what is the procedure in multiplier adder tree. Can you please tell me the whats the procedure of these. If you are busy can you please send me the some links or resource regarding above things.

Thank You

**Comment by ArjunaDeSoysa** [comment]
Dear @doonny , @aazz44ss , @hammadj can i know the what is these parameters are? Please help me to find outthis one. Thank you.
![1234](https://user-images.githubusercontent.com/35629589/39224376-4789a6f8-4871-11e8-9284-2fc8f8820749.PNG)

**Comment by aazz44ss** [comment]
maybe you need to read some document about convolution .

**Comment by ArjunaDeSoysa** [comment]
Okay i got it. Thank you.
