### ISSUE TITLE
how to run the exemple on my card ???

### ISSUE THREAD

**Issue by Fnajjar** [doonny/PipeCNN#74]
I want to test the Pipe CNN on an Attila Arria 10 GX card with an Intel SDK open CL v17.1. I did the implentation and it's working!
Stil, I want to do the demo on my card:
hwo can I do that?
 - Shall I download the imagNet database? 
 - Shall I upload caffe? and since I am using ubunto 16.04 shall I upload cuda toolbox 8.0 with it?
Please help! I wan't to simulate the demo!

thank you very much for the further explanation.

**Comment by manojrohit** [comment]
Hello @Fnajjar 

Install the Intel SDK for openCL. This guide might help you.(https://www.altera.com/en_US/pdfs/literature/hb/opencl-sdk/aocl_getting_started.pdf)

Install OpenCV.

As this repo supports Intel opencl v16.1, make necessary changes for v17.1. 

Download the imgaenet 2012 validation set.

**Comment by Fnajjar** [comment]
Thank you very much for your answer @manojrohit, but how can I download the imgaenet 2012 validation set??
I didn't find it in the ImageNet website unfortunatly

**Comment by manojrohit** [comment]
You can download by registering in http://www.image-net.org/download-images.

**Comment by Fnajjar** [comment]
Thank you @manojrohit,  
So ones I upload the validation images 2012 from the imageNet, do I extract the folder in the PipeCNN-master/data/imagenet?
Is there modifications to make in the file's code?

**Comment by manojrohit** [comment]
If you go through the host cpp file, in line 71 you can see 
char  picture_file_path_head[100] ="/home/dwang/Work/imagenet/ilsvrc2012/ILSVRC2012_img_val/ILSVRC2012_val_";

You can extract the validation data and change the path in host program.

**Comment by Fnajjar** [comment]
@manojrohit thank you so much it's finally working 
that was so helpful :)

**Comment by doonny** [comment]
Definitely YES : )

**Comment by Fnajjar** [comment]
Thank you @doonny  for this great news! :)
Do you have previous work or some advices on how shall I proceed? 
Thank you very much for the help

**Comment by roddregs** [comment]
@Fnajjar @manojrohit @doonny 
I was using DE1-SoC Cyclone V board and successfully compiled and run in the board the PipeCNN using PLATFORM=arm32 and flow=hw which only read one image file.
And now, I tried to enable OpenCV to experiment loading multiple images from Imagenet 2012 validation set.
I set USE_OPENCV = 1 in the Makefile and installed OpenCV 2.4.9 in my PC (Ubuntu 16.04).
When I compiled, I got the following error that says:
 libopencv_core.so :file not recognized: File format not recognized

![image](https://user-images.githubusercontent.com/35408397/41183236-329e9a92-6bac-11e8-8eb6-d0770362ffc9.png)
Any suggestion on how to solve this error? Is OpenCV 2.4.9 not compatible with the current set-up of PipeCNN?
Thank you very much.

**Comment by doonny** [comment]
First, you need to cross-compile your opencv lib for arm. Your opencv installed is for PC not for arm

**Comment by arun0303** [comment]
Hi Sir,
how to change cross compile OpenCV  lib for arm?

**Comment by arun0303** [comment]
Hi Sir,
how to cross compile OpenCV lib for arm?

**Comment by Wanghaoshu** [comment]
How to use VNC for image visualization on de10_nano board @doonny @manojrohit @roddregs

**Comment by doonny** [comment]
I am assuming this problem has been solved.
