### ISSUE TITLE
ERROR:  usr/local/lib/libopencv_co.so: file not recognized: file format not recognized

### ISSUE THREAD

**Issue by DasunBhanuka** [doonny/PipeCNN#77]
@doonny @thinkoco @aazz44ss @hammadj, Does this error come up because of a compatibility issue with the version I am using for OpenCV (which is 4.0.0)?

**Comment by DasunBhanuka** [comment]
@doonny @thinkoco @aazz44ss @hammadj, which OpenCV are you using?

**Comment by DasunBhanuka** [comment]
I am sorry, I meant OpenCV, I've tranferred from OpenCV 4.0.0 to OpenCV 3.3.1. But still gets the same error..  `arm-linux-gnueabihf-g++ .. usr/local/lib/libopencv_co.so: file not recognized: file format not recognized`. After a while, I found that this is due to an issue in building OpenCV for ARM..

**Comment by DasunBhanuka** [comment]
Dear  @doonny,
This is the error I get. Can you tell me **which OpenCV version you used** for that, so that I can try it also and see just in case..
![screenshot from 2018-05-04 14-00-24](https://user-images.githubusercontent.com/38661801/39616258-b1a05dd6-4fa4-11e8-8bdf-9affd9175c45.png)

**Comment by roddregs** [comment]
@DasunBhanuka 
Were you able to solve this error? Encountered same error here..
How do you solve it?
Thanks.

**Comment by Enshall** [comment]
file format issues always mean ur compiler was wrong.
ur path of opencv in makefile  is /usr/local/opencv-arm,  but what actually works is  usr/local/lib/..
so, the answer is just in ur logs.

**Comment by DasunBhanuka** [comment]
@Enshall  Were you able to successfully implement the PipeCNN on a DE1SoC including OpenCV part?

**Comment by Enshall** [comment]
@DasunBhanuka Yeah, I made it.

**Comment by DasunBhanuka** [comment]
@Enshall  Can you please tell me what you did to solve this issue ? I am stuck with this for weeks.. It would be a great help..

**Comment by DasunBhanuka** [comment]
@Enshall Did you encounter the same issue with DE1SOC.. ?  In case you want, my email is lokubaba321@gmail.com

**Comment by Enshall** [comment]
@DasunBhanuka 
I don`t have a problem with u or opencv, but I guess ur opencv compilation didn`t success(/usr/local/opencv-arm exits?).
what now actually works is ur x86 version, arm-gcc can`t recognized.
so recompile ur opencv with arm-gcc or just download a copy may be worked.

**Comment by DasunBhanuka** [comment]
@Enshall 
Yes, Problem might be in "arm-gcc" . Couldn't find a compatible version for DE1SOC..
How did you install arm-gcc ?

**Comment by SudharanTJ** [comment]
@Enshall 
I am having the same problem as well. Did you get the same error as well.. ? The problem is in the `arm-linux-gnueabihf` How did you get it to work ?

**Comment by Enshall** [comment]
@DasunBhanuka
ur compiler is ok. 
ur log says there is no opencv_core.lib in /usr/local/opencv-arm,  that`s means u didn`t corss-compile opencv successfully or ur path in makefile is wrong. u can check them first.  
@SudharanTJ
Cross compile opencv with CMake, modify opencv path in ur makefile (OCV_INCLUDES OCV_LIBDIRS).

**Comment by arun0303** [comment]
hi,
I am using DE10 Standard kit i am facing the following error kindly help me. 

Thanks 
ARUN
![for_doony](https://user-images.githubusercontent.com/41463803/43514287-80a55fa8-959d-11e8-8a53-4f830333a0e8.png)

**Comment by arun0303** [comment]
hi @DasunBhanuka  kindly help me on this

**Comment by doonny** [comment]
I am assuming this problem has been solved.
