### ISSUE TITLE
Undefined Reference CV::_OutputArray::_OutputArray(cv::Mat&)

### ISSUE THREAD

**Issue by DasunBhanuka** [doonny/PipeCNN#79]
Dear @doonny,
 I am getting this error while compiling Makefile using OpenCV 3.3.0..
![11111](https://user-images.githubusercontent.com/38661801/39630304-2d11f1c6-4fd9-11e8-87ea-f41130f505a5.png)

**Comment by ArjunaDeSoysa** [comment]
Same issue for me also. Do you have any ideas  @thinkoco ,  @hammadj,  @davenso?

**Comment by manojrohit** [comment]
You can see opencv includes defined in the host file (lines 29, 30, 31). You can change them based on the opencv version you have installed. 

Also in the Makefile, you can notice the opencv includes and libs defined. Change them based on your version.

**Comment by DasunBhanuka** [comment]
Dear @manojrohit, 
How did you configure yours? What is your OpenCV version?

**Comment by DasunBhanuka** [comment]
Dear @doonny @manojrohit,

We also have trouble defining paths for **arm-linux-gnueabihf** Do you have any tips for that?

**Comment by manojrohit** [comment]
I have install the OpenCV 2 version to configure. I tried to use the same paths specified in the program. I use x86 as my host not arm. So no idea about that.

**Comment by DasunBhanuka** [comment]
Dear @doonny, Have you tried implementing this on **ARM architecture with OpenCV enabled** ? This works flawlessly on x86, (and ARM architecture with OpenCV disabled) but gives a bunch of errors on ARM with OpenCV.

**Comment by doonny** [comment]
We have tested PipeCNN with OpenCV on the SoC-FPGA.  You could install an ubuntu minimal FS and just use apt-get command to install all the prebuild opencv libs. We used this one:
https://rcn-ee.com/rootfs/eewiki/minfs/ubuntu-16.04.3-minimal-armhf-2017-12-09.tar.xz

**Comment by DasunBhanuka** [comment]
Dear @doonny,
Ok, we'll try with OpenCV 2.4.9.. We got prebuild libs from here.. [](https://github.com/praveen-palanisamy/OpenCV-2.4.9-for-arm) 
Where did you get prebuild opencv libs ?

**Comment by doonny** [comment]
We directly build all libs on our boards.

**Comment by DasunBhanuka** [comment]
Did you use `apt-get install gcc-4.7-arm-linux-gnueabihf` for installing arm libraries or use a **gcc-linaro-6.4.1-2017.11-x86_64_arm-linux-gnueabihf** package ?

**Comment by arun0303** [comment]
@DasunBhanuka 
Hai,
Did you solved the above issue i am also facing the same error. Please help me if you solved the error
Thanks
ARUN

**Comment by doonny** [comment]
I am assuming this problem has been solved.
