### ISSUE TITLE
Inference result not displayed.

### ISSUE THREAD

**Issue by gandautama** [doonny/PipeCNN#8]
HI how to print:
" The inference result is n02123045 tabby, tabby cat   (the prob is 56.00) ." at last in your documentation? 
Thanks in advance..
Regards,
Ganda.

**Comment by nilesh441** [comment]
I also faced this problem but I think latest commit contains this change.

**Comment by gandautama** [comment]
Ok thanks i will close this issue.

**Comment by doonny** [comment]
@gandautama Please close this issue if it is correctly fixed.

**Comment by gandautama** [comment]
Thanks, I have pulled the last commit build it with no error. Sorry for the delay.

**Comment by gandautama** [comment]
I forked and put the result for DE-10 NANO using OpenCL-17. [the output is here](https://github.com/gandautama/PipeCNN/blob/master/eclipse/pipe_2_0/out.txt).

**Comment by doonny** [comment]
@gandautama Great THX. Which hw configurations are you using ?

**Comment by gandautama** [comment]
I am using FPGA Board configuration (not simulation), [ here is the hardware param](https://github.com/gandautama/PipeCNN/blob/master/eclipse/pipe_2_0/device/hw_param.cl).
