### ISSUE TITLE
single Merged WI kernel vs multiple kernels

### ISSUE THREAD

**Issue by manojrohit** [doonny/PipeCNN#82]
Hello @doonny ,
I am trying to merge all the kernels into single WI kernel. But do you think this strategy would be more effective? I think passing the values using local memory would be faster than OpenCL channels?  What do you think would be the challenges in the implementation of single merged Kernel?

**Comment by doonny** [comment]
I think a single kernel would also work, but hard to say which one is more efficient. Need to explore the results before making such conclusion.
