### ISSUE TITLE
how to generate the fc8 file

### ISSUE THREAD

**Issue by Fnajjar** [doonny/PipeCNN#88]
hi, 
I am trying to run an other image database with the Pipecnn.
I generated the Weights.dat but i am having wrong recognitions, and probabilities.
So I suspected a problem with the fc8 file.
Could you please tell me, how to generate an fc8 file for the new dataset?

**Comment by manojrohit** [comment]
I think the procedure is mentioned in https://github.com/doonny/PipeCNN/tree/master/data

**Comment by manojrohit** [comment]
You are on OpenCV mode. fc8.dat is output from the inference of image.dat, which I bielieve is the binary of (https://github.com/doonny/PipeCNN/tree/master/data/picture). 

Are you using the same  https://github.com/doonny/PipeCNN/blob/master/data/imagenet/synset_words.txt?

**Comment by Fnajjar** [comment]
hey @manojrohit , thank you for the answer
No actually, since I am using the german traffic sign recognetion database GTSRB, I am trying to adopt the PipeCNN to treat it I uploaded a caffemodel I converted the weights thanks to the matlab script, then used the labels for the new base, val.txt too

but still having wrong recognition, no probabilities nor accuracy.
besides, if I put the size of the new weights file it does not work, only with the size of imagenet weight's size it runs

![1](https://user-images.githubusercontent.com/38285230/42386058-bbcb53da-813e-11e8-8c6a-065c48fdd745.png)
![2](https://user-images.githubusercontent.com/38285230/42386060-bbef7828-813e-11e8-94ca-f7910b9ac4b9.png)
![3](https://user-images.githubusercontent.com/38285230/42386061-bc19193a-813e-11e8-9fe4-1c0d5748cabb.png)
![4](https://user-images.githubusercontent.com/38285230/42386062-bc31e4e2-813e-11e8-9e5d-be7ef0e3dcac.png)
![weight](https://user-images.githubusercontent.com/38285230/42385775-0943717a-813e-11e8-822b-b20fd3bc32f1.png)


I think there are parameters to change but I don't know!
any ideas please

**Comment by Fnajjar** [comment]
hey @manojrohit , thank you for the answer
No actually, since I am using "the german traffic sign recognetion database GTSRB", I am trying to adopt the PipeCNN to treat it I uploaded a caffemodel I converted the weights thanks to the matlab script, then used the labels for the new base, val.txt too

but still having wrong recognition, no probabilities nor accuracy.
besides, if I put the size of the new weights file it does not work, only with the size of imagenet weight's size it runs

![1](https://user-images.githubusercontent.com/38285230/42386058-bbcb53da-813e-11e8-8c6a-065c48fdd745.png)
![2](https://user-images.githubusercontent.com/38285230/42386060-bbef7828-813e-11e8-94ca-f7910b9ac4b9.png)
![3](https://user-images.githubusercontent.com/38285230/42386061-bc19193a-813e-11e8-9fe4-1c0d5748cabb.png)
![4](https://user-images.githubusercontent.com/38285230/42386062-bc31e4e2-813e-11e8-9e5d-be7ef0e3dcac.png)
![weight](https://user-images.githubusercontent.com/38285230/42385775-0943717a-813e-11e8-822b-b20fd3bc32f1.png)


I think there are parameters to change but I don't know!
any ideas please

**Comment by manojrohit** [comment]
I think there is a small change from original caffe net. The MATLAB script would generate weights according to fc8-1000 because original caffenet output layer has 1000 and not 1024. This might be the problem.

**Comment by doonny** [comment]
@manojrohit thx for the answer.

**Comment by Fnajjar** [comment]
Hi @manojrohit and @doonny thank you very much for the answers.
I replaced 1024 with 1000 in the layer_config.h, and in the main.cpp; and choose the weights according to fc8-10000, but no changes acutally I am still having wrong answers(all inferences are false , wrong probabilities and false labels), and no accuracy 
here below you find some screen shot first for the 1024 config
![1](https://user-images.githubusercontent.com/38285230/42560715-a29a96ca-84f7-11e8-99f3-2cba2e0ae81c.png)
![with1024-1](https://user-images.githubusercontent.com/38285230/42560716-a2ba3958-84f7-11e8-9915-72f5bf2373d1.png)
![with1024-2](https://user-images.githubusercontent.com/38285230/42560717-a2d2e2aa-84f7-11e8-837b-e140d4f237d0.png)
![with 1024-3](https://user-images.githubusercontent.com/38285230/42560718-a2eb4778-84f7-11e8-956b-8052b23f9f3c.png)

and these are for the 1000 config 

![1](https://user-images.githubusercontent.com/38285230/42560755-ba5faf3e-84f7-11e8-8073-421159366eba.png)
![with1000](https://user-images.githubusercontent.com/38285230/42560756-ba757f6c-84f7-11e8-98de-2573e6ce180a.png)
![with1000-1](https://user-images.githubusercontent.com/38285230/42560757-ba8ad4ca-84f7-11e8-85b1-dcdb925089d4.png)
![with1000-3](https://user-images.githubusercontent.com/38285230/42560758-baa293f8-84f7-11e8-8c10-9f2752c20c00.png)

Thank for your exchange

**Comment by manojrohit** [comment]
The errors might be because of the way you have trained the model. Did you use CaffeNet and not AlexNet? Some layers are different in both.

My suggestion is to perform a CPU emulation for one particular image in the database and compare the outputs layerwise with FPGA.

**Comment by Fnajjar** [comment]
Well actually I used a pre trained model GTSRB-caffe-model (https://github.com/magnusja/GTSRB-caffe-model) using the deep learning model AlexNet. 
Meantime, I am going to try your suggestion.
Thank you so much @manojrohit

**Comment by manojrohit** [comment]
PipeCNN is performing the inference of caffenet. The difference between caffenet and alexnet is the order of pooling and norm layers in Layer 1 and Layer 2.

**Comment by Fnajjar** [comment]
@manojrohit first of all I want to thank you for your answers, you were right.
I checked the deploy.prototxt and the order of the 2 first layers was reversed. That makes sense, and it's much more clear.
Otherwise, I was wondering if there are some changes to do in pipeCNN code to adapt it to the Alexnet model, since in the documentation it's always written (AlexNet(CaffeNet)) seems like they are similar however they are  not.
 
Or, what can you advise me? shall I retrain the model with caffenet??

@manojrohit thank you so much again for the valuable help :)

![prototxt](https://user-images.githubusercontent.com/38285230/42584544-b9b4498c-8533-11e8-9fc3-70ac8d3e9421.png)

**Comment by Fnajjar** [comment]
@manojrohit first of all I want to thank you for your answers, you were right.
I checked the deploy.prototxt and the order of the 2 first layers was reversed. That makes sense, and it's much more clear.
Otherwise, I was wondering if there are some changes to do in pipeCNN code to adapt it to the Alexnet model, since in the documentation it's always written (AlexNet(CaffeNet)) seems like they are similar however they are  not.
 
Or, what can you advise me? shall I retrain the model with caffenet??

@manojrohit thank you so much again for the valuable help :)

![prototxt](https://user-images.githubusercontent.com/38285230/42584544-b9b4498c-8533-11e8-9fc3-70ac8d3e9421.png)

**Comment by manojrohit** [comment]
I think you should retrain the model to CaffeNet. It would take some effort to change it to AlexNet.

**Comment by Fnajjar** [comment]
Hey all; 
I am new to caffe and I am training the model with caffenet, and I was wondering If it's okay that I am having this kind of results
Thank you for your advices!! It's so helpful :)
![train1](https://user-images.githubusercontent.com/38285230/42928072-a3bf348a-8b36-11e8-8418-4104c025fa47.png)
![train2](https://user-images.githubusercontent.com/38285230/42928073-a3d4e046-8b36-11e8-8801-7e514b1c62df.png)

**Comment by doonny** [comment]
Hi, please refer to the README in the data folder.
