### ISSUE TITLE
Board Performance 

### ISSUE THREAD

**Issue by SmartRoof** [doonny/PipeCNN#9]
Regarding to the statement of pipeCNN has been tested in the following boards:
- Terasic's DE5-net (Stratix-IV A7 FPGA)
- Terasic's DE5a-net (Arria-10 1150 FPGA)
- Terasic's DE1-soc (Cyclone-V SEA5 FPGA)
- Terasic's DE10-standard (Cyclone-V SXC6 FPGA)
- Xilinx's KCU1500 (XCKU115 FPGA)

May I know where can I get the performance and cost information of these board, as only the performance of DE5-net is listed in the paper.
Thank You

**Comment by doonny** [comment]
Hi please check the latest update. We will add more info for more boards soon.
