### ISSUE TITLE
DE1-SoC parameters

### ISSUE THREAD

**Issue by 0x47** [doonny/PipeCNN#95]
Hello,

In the [README.md](https://github.com/doonny/PipeCNN/blob/master/README.md#L34) file it says that the execution time for AlexNet on the DE1-SoC is 150 ms. Can you provide the configuration for the hw_param.cl file to achieve 150 ms? I tried with `VEC_SIZE = 4`, `LANE_NUM = 4`, `CONV_GP_SIZE_X = 7` and `PIPE_DEPTH = 6` but I can only achieve 351.607 ms. Increasing `LANE_NUM` further (e.g. 16 as in the default setting) is not possible because of the low hardware resources of the DE1-SoC.

**Comment by aazz44ss** [comment]
It also depend on Fmax and batch size you use.
What is your Fmax?

**Comment by 0x47** [comment]
The batch size is 1 and the kernel clock frequency is `139.56 MHz` taken from the `quartus_sh_compile.log` file.

**Comment by 0x47** [comment]
It turns out that removing the `--profile` parameter from the Makefile solves this issue and allows setting `VEC_SIZE = 8` and `LANE_NUM = 8`. Thanks and have a nice day!
