### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by spstrademark** [doonny/PipeCNN#99]
Hello,

In Soc EDS when i type make in the project directory i get the following error -  
g++   ./host/main.o ../common/ocl_util.o ../common/timer.o -o run.exe -LC:\intelFPGA\17.1\hld\board\terasic\de10_nano\arm32\lib -LC:/intelFPGA/17.1/hld/host/arm32/lib -Wl,--no-as-needed -lalteracl -lintel_soc32_mmd -lelf -lstdc++
/usr/lib/gcc/x86_64-pc-cygwin/4.9.2/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lalteracl
/usr/lib/gcc/x86_64-pc-cygwin/4.9.2/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lintel_soc32_mmd
/usr/lib/gcc/x86_64-pc-cygwin/4.9.2/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lelf
collect2: error: ld returned 1 exit status 

How can this be resolved?
I am fairly new to FPGA and this is my first FPGA board but i did not see this issue elsewhere and i apologize if the answer is rather obvious.

Thank you for your time!

Best regards,
Stanko Stankov

**Comment by doonny** [comment]
I am assuming this problem is solved.
